# Generated by Django 6.1.1 on 2026-10-05 01:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('syst', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'صنف', 'verbose_name_plural': 'الأصناف'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'إشعار', 'verbose_name_plural': 'الإشعارات'},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'verbose_name': 'موقع', 'verbose_name_plural': 'المواقع'},
        ),
        migrations.AlterModelOptions(
            name='siteinventory',
            options={'verbose_name': 'مخزون موقع', 'verbose_name_plural': 'مخزون المواقع'},
        ),
        migrations.AlterModelOptions(
            name='transferlog',
            options={'verbose_name': 'سجل حركة', 'verbose_name_plural': 'سجل الحركة'},
        ),
        migrations.AlterModelOptions(
            name='transferrequest',
            options={'verbose_name': 'طلب نقل', 'verbose_name_plural': 'طلبات النقل'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'مستخدم', 'verbose_name_plural': 'المستخدمون'},
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('MATERIAL', 'مادة بناء'), ('EQUIPMENT', 'معدة/آلة'), ('TOOL', 'أداة عمل')], max_length=20, verbose_name='نوع الصنف'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='مقروء'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(verbose_name='النص'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=200, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='site',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة'),
        ),
        migrations.AlterField(
            model_name='siteinventory',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syst.item', verbose_name='الصنف'),
        ),
        migrations.AlterField(
            model_name='siteinventory',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='syst.site', verbose_name='الموقع'),
        ),
        migrations.AlterField(
            model_name='transferlog',
            name='action_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='بواسطة'),
        ),
        migrations.AlterField(
            model_name='transferlog',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظة'),
        ),
        migrations.AlterField(
            model_name='transferlog',
            name='status_changed_to',
            field=models.CharField(max_length=20, verbose_name='الحالة الجديدة'),
        ),
        migrations.AlterField(
            model_name='transferlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='الوقت'),
        ),
        migrations.AlterField(
            model_name='transferlog',
            name='transfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syst.transferrequest', verbose_name='طلب النقل'),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='أنشأه'),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syst.item', verbose_name='الصنف'),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='الكمية'),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='source_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_sent', to='syst.site', verbose_name='من موقع (المصدر)'),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'بانتظار الموافقة'), ('APPROVED', 'مقبول'), ('IN_TRANSIT', 'جاري النقل'), ('DELIVERED', 'تم الاستلام'), ('REJECTED', 'مرفوض')], default='PENDING', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='target_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_received', to='syst.site', verbose_name='إلى موقع (المستلم)'),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تحديث'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='custom_user_set', to='auth.group', verbose_name='المجموعات'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'الإدارة العامة'), ('SITE_ADMIN', 'مدير موقع')], default='SITE_ADMIN', max_length=20, verbose_name='الصلاحية'),
        ),
        migrations.AlterField(
            model_name='user',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='syst.site', verbose_name='الموقع'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='custom_user_set_permissions', to='auth.permission', verbose_name='صلاحيات المستخدم'),
        ),
    ]
